export enum Countries {
  Argentina = "AR",
  Boliva = "BO",
  Brasil = "BR",
  Chile = "CL",
  Colombia = "CO",
  CostaRica = "CR",
  Dominicana = "DO",
  Ecuador = "EC",
  Guatemala = "GT",
  Honduras = "HN",
  Mexico = "MX",
  Nicaragua = "NI",
  Panama = "PA",
  Paraguay = "PY",
  Peru = "PE",
  ElSalvador = "SV",
  Uruguay = "UY",
  Venezuela = "VE",
}
